---
- name: Install Vim with clipboard support
  apt:
    name: vim-gtk3
  tags:
    - editor

- name: Set Vim as default editor
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim
  tags:
    - editor
