---
- name: Configure Kali Linux System
  hosts: all
  connection: local
  become: yes
  vars_files:
    - vars/all.yml
  pre_tasks:
    - import_tasks: tasks/pretasks.yml
  roles:
    - role: apt
    - role: base
    - role: hostname
    - role: keyboard
    - role: shell
    - role: editor
    - role: ufw
    - role: tilix
    - role: nvidia
      when: target == "desktop"
