---
# GDM uses its own dconf database.
# Reference: https://gitlab.gnome.org/GNOME/gdm/-/issues/695
- block:
  - name: Set keyboard layout to US International
    dconf:
      key: "/org/gnome/desktop/input-sources/sources"
      value: "[('xkb', 'us+intl')]"
    tags:
      - gdm

  - name: Enable tap to click for Laptop target
    dconf:
      key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
      value: "true"
    when: target == "laptop"
    tags:
      - gdm

  become: yes
  become_user: Debian-gdm
