---
- name: Push additional apt repositories
  copy:
    src: "{{ item }}"
    dest: /etc/apt/sources.list.d
    mode: '644'
  with_fileglob: '*.list'
  register: apt_sources_list
  tags:
    - apt

- name: Update package lists if new repository was added
  apt:
    update_cache: yes
  when: apt_sources_list.changed
  tags:
    - apt

- name: Update package lists if older than 1 hour
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - apt
