galaxy_info:
  author: github.com/hakbyte
  description: Enable cedilla for the English input language
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - bullseye
