---
- name: Install base packages
  apt:
    name: "{{ pkg }}"
  tags:
    - base

- name: Install base packages (*.deb)
  apt:
    deb: "{{ item }}"
  loop: "{{ deb }}"
  tags:
    - base
    - deb

- name: Enable and start bluetooth service
  service:
    name: bluetooth
    enabled: yes
    state: started
  tags:
    - base
