---
- name: Install base packages
  apt:
    name: "{{ pkg }}"
  tags:
    - base

- name: Install base packages (*.deb)
  apt:
    deb: "{{ item }}"
  loop: "{{ deb }}"
  tags:
    - base
    - deb

- name: Download wallpapers
  git:
    repo: https://github.com/hakbyte/wallpapers
    dest: /usr/share/backgrounds/{{ username }}
    depth: 1
  tags:
    - base

- name: Enable and start bluetooth service
  service:
    name: bluetooth
    enabled: yes
    state: started
  tags:
    - base
